#!/bin/bash

eb setenv POSTGRES_HOST=$POSTGRES_HOST \
  POSTGRES_DB=$POSTGRES_DB \
  POSTGRES_TEST_DB=$POSTGRES_TEST_DB \
  POSTGRES_USER=$POSTGRES_USER \
  POSTGRES_PASSWORD=$POSTGRES_PASSWORD \
  ENV=$ENV \
  BCRYPT_PASSWORD=$BCRYPT_PASSWORD \
  SALT_ROUNDS=$SALT_ROUNDS \
  TOKEN_SECRET=$TOKEN_SECRET